// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlcjopawbjhnlgxvixsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsY2pvcGF3YmpobmxneHZpeHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTkxNDQsImV4cCI6MjA2MTQ5NTE0NH0.pjzYqJDCf4O-qS2GQoOS488jI_usno9LnLMMKHXn9ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);